src/eShopLegacyMVC/Models/CatalogType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eShopLegacyMVC.Models
{
    public class CatalogType
    {
        public int Id { get; set; }
        public string Type { get; set; }
    }
}

src/eShopLegacyMVC/Controllers/CatalogController.cs
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using eShopLegacyMVC.Models;
using eShopLegacyMVC.Services;
using log4net;

namespace eShopLegacyMVC.Controllers
{
    public class CatalogController : Controller
    {
        private static readonly ILog _log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private ICatalogService service;

        public CatalogController(ICatalogService service)
        {
            this.service = service;
        }

        // GET /[?pageSize=3&pageIndex=10]
        public ActionResult Index(int pageSize = 10, int pageIndex = 0)
        {
            _log.Info($"Now loading... /Catalog/Index?pageSize={pageSize}&pageIndex={pageIndex}");
            var paginatedItems = service.GetCatalogItemsPaginated(pageSize, pageIndex);
            ChangeUriPlaceholder(paginatedItems.Data);
            return View(paginatedItems);
        }

        // GET: Catalog/Details/5
        public ActionResult Details(int? id)
        {
            _log.Info($"Now loading... /Catalog/Details?id={id}");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CatalogItem catalogItem = service.FindCatalogItem(id.Value);
            if (catalogItem == null)
            {
                return HttpNotFound();
            }
            AddUriPlaceHolder(catalogItem);

            return View(catalogItem);
        }

        // GET: Catalog/Create
        public ActionResult Create()
        {
            _log.Info($"Now loading... /Catalog/Create");
            ViewBag.CatalogBrandId = new SelectList(service.GetCatalogBrands(), "Id", "Brand");
            ViewBag.CatalogTypeId = new SelectList(service.GetCatalogTypes(), "Id", "Type");
            return View(new CatalogItem());
        }

        // POST: Catalog/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,Price,PictureFileName,CatalogTypeId,CatalogBrandId,AvailableStock,RestockThreshold,MaxStockThreshold,OnReorder")] CatalogItem catalogItem)
        {
            _log.Info($"Now processing... /Catalog/Create?catalogItemName={catalogItem.Name}");
            if (ModelState.IsValid)
            {
                service.CreateCatalogItem(catalogItem);
                return RedirectToAction("Index");
            }

            ViewBag.CatalogBrandId = new SelectList(service.GetCatalogBrands(), "Id", "Brand", catalogItem.CatalogBrandId);
            ViewBag.CatalogTypeId = new SelectList(service.GetCatalogTypes(), "Id", "Type", catalogItem.CatalogTypeId);
            return View(catalogItem);
        }

        // GET: Catalog/Edit/5
        public ActionResult Edit(int? id)
        {
            _log.Info($"Now loading... /Catalog/Edit?id={id}");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CatalogItem catalogItem = service.FindCatalogItem(id.Value);
            if (catalogItem == null)
            {
                return HttpNotFound();
            }
            AddUriPlaceHolder(catalogItem);
            ViewBag.CatalogBrandId = new SelectList(service.GetCatalogBrands(), "Id", "Brand", catalogItem.CatalogBrandId);
            ViewBag.CatalogTypeId = new SelectList(service.GetCatalogTypes(), "Id", "Type", catalogItem.CatalogTypeId);
            return View(catalogItem);
        }

        // POST: Catalog/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Price,PictureFileName,CatalogTypeId,CatalogBrandId,AvailableStock,RestockThreshold,MaxStockThreshold,OnReorder")] CatalogItem catalogItem)
        {
            _log.Info($"Now processing... /Catalog/Edit?id={catalogItem.Id}");
            if (ModelState.IsValid)
            {
                service.UpdateCatalogItem(catalogItem);
                return RedirectToAction("Index");
            }
            ViewBag.CatalogBrandId = new SelectList(service.GetCatalogBrands(), "Id", "Brand", catalogItem.CatalogBrandId);
            ViewBag.CatalogTypeId = new SelectList(service.GetCatalogTypes(), "Id", "Type", catalogItem.CatalogTypeId);
            return View(catalogItem);
        }

        // GET: Catalog/Delete/5
        public ActionResult Delete(int? id)
        {
            _log.Info($"Now loading... /Catalog/Delete?id={id}");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CatalogItem catalogItem = service.FindCatalogItem(id.Value);
            if (catalogItem == null)
            {
                return HttpNotFound();
            }
            AddUriPlaceHolder(catalogItem);

            return View(catalogItem);
        }

        // POST: Catalog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _log.Info($"Now processing... /Catalog/DeleteConfirmed?id={id}");
            CatalogItem catalogItem = service.FindCatalogItem(id);
            service.RemoveCatalogItem(catalogItem);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _log.Debug($"Now disposing");
            if (disposing)
            {
                service.Dispose();
            }
            base.Dispose(disposing);
        }

        private void ChangeUriPlaceholder(IEnumerable<CatalogItem> items)
        {
            foreach (var catalogItem in items)
            {
                AddUriPlaceHolder(catalogItem);
            }
        }

        private void AddUriPlaceHolder(CatalogItem item)
        {
            item.PictureUri = this.Url.RouteUrl(PicController.GetPicRouteName, new { catalogItemId = item.Id }, this.Request.Url.Scheme);            
        }
    }
}

src/eShopLegacyMVC/Controllers/CatalogStatisticsController.cs
using System.Linq;
using System.Web.Mvc;
using eShopLegacyMVC.Services;
using eShopLegacyMVC.ViewModel;

namespace eShopLegacyMVC.Controllers
{
    public class CatalogStatisticsController : Controller
    {
        private ICatalogService service;

        public CatalogStatisticsController(ICatalogService service)
        {
            this.service = service;
        }

        [ChildActionOnly]
        public ActionResult Index()
        {
            var viewModel = new CatalogStatisticsViewModel
            {
                NumberOfBrands = service.GetCatalogBrands().Count(),
                NumberOfCategories = service.GetCatalogTypes().Count(),
                NumberOfItems = (int)service.GetCatalogItemsPaginated(1000, 0).TotalItems
            };
            return View(viewModel);
        }
    }
}

src/eShopLegacyMVC/Views/Catalog/CatalogPaging.cshtml
@model eShopLegacyMVC.ViewModel.PaginatedItemsViewModel<eShopLegacyMVC.Models.CatalogItem>

<div class="esh-pager">
    <div class="container-fluid">
        <article class="esh-pager-wrapper row">
            <nav>

                @if (Model.ActualPage > 0)
                {
                    @Html.ActionLink("Previous", "Index", new { pageSize = Model.ItemsPerPage, pageIndex = Model.ActualPage - 1 }, new { @class = "esh-pager-item esh-pager-item--navigable" })
                }
                else
                {
                    @Html.ActionLink("Previous", "Index", new { pageSize = Model.ItemsPerPage, pageIndex = Model.ActualPage - 1 }, new { @class = "esh-pager-item esh-pager-item--navigable esh-pager-item--hidden" })
                }

                <span class="esh-pager-item">
                    Showing @Model.ItemsPerPage of @Model.TotalItems products - Page @(Model.ActualPage + 1) - @Model.TotalPages
                </span>

                @if (Model.ActualPage < Model.TotalPages - 1)
                {
                    @Html.ActionLink("Next", "Index", new { pageSize = Model.ItemsPerPage, pageIndex = Model.ActualPage + 1 }, new { @class = "esh-pager-item esh-pager-item--navigable" })
                }
                else
                {
                    @Html.ActionLink("Next", "Index", new { pageSize = Model.ItemsPerPage, pageIndex = Model.ActualPage + 1 }, new { @class = "esh-pager-item esh-pager-item--navigable esh-pager-item--hidden" })
                }

            </nav>
        </article>
    </div>
</div>

src/eShopLegacyMVC/Views/Catalog/CatalogTable.cshtml
@model IEnumerable<eShopLegacyMVC.Models.CatalogItem>

<table class="table">
    <thead>
        <tr class="esh-table-header">
            <th>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CatalogBrand.Brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CatalogType.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PictureFileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AvailableStock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RestockThreshold)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxStockThreshold)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
            <tr>
                <td>
                    <img class="esh-thumbnail" src="@item.PictureUri" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CatalogBrand.Brand)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CatalogType.Type)
                </td>
                <td class="esh-table-price">
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PictureFileName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AvailableStock)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RestockThreshold)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxStockThreshold)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "esh-table-link" }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "esh-table-link" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "esh-table-link" })
                </td>
            </tr>
        }
    </tbody>

</table>

src/eShopLegacyMVC/Views/Catalog/Create.cshtml
@model eShopLegacyMVC.Models.CatalogItem

@{
    ViewBag.Title = "Create";
}

<h2 class="esh-body-title">Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CatalogBrandId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.DropDownList("CatalogBrandId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CatalogBrandId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CatalogTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.DropDownList("CatalogTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CatalogTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PictureFileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4 esh-form-information">
                Uploading images not allowed for this version.
                @*@Html.TextBoxFor(model => model.PictureFileName, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.ValidationMessageFor(model => model.PictureFileName, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AvailableStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.AvailableStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AvailableStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RestockThreshold, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.RestockThreshold, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RestockThreshold, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxStockThreshold, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.MaxStockThreshold, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxStockThreshold, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-3 text-right esh-button-actions">
                @Html.ActionLink("[ Cancel ]", "Index", null, new { @class = "btn esh-button esh-button-secondary" })
                <input type="submit" value="[ Create ]" class="btn esh-button esh-button-primary" />
            </div>
        </div>
    </div>
}

<div>
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/eShopLegacyMVC/Views/Catalog/Delete.cshtml
@model eShopLegacyMVC.Models.CatalogItem

@{
    ViewBag.Title = "Delete";
}

<h2 class="esh-body-title">Delete</h2>

<div class="container">
    <h3>Are you sure you want to delete this?</h3>
    <div class="row">
        <img class="col-md-6 esh-picture" src="@Model.PictureUri" />
        <dl class="col-md-6 dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CatalogBrand.Brand)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CatalogBrand.Brand)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CatalogType.Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CatalogType.Type)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PictureFileName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PictureFileName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AvailableStock)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AvailableStock)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.RestockThreshold)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RestockThreshold)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MaxStockThreshold)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MaxStockThreshold)
            </dd>

            <dt>
            </dt>

            <dd class="text-right esh-button-actions">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ActionLink("[ Cancel ]", "Index", null, new { @class = "btn esh-button esh-button-secondary" })
                    <button type="submit" class="btn esh-button esh-button-primary">[ Delete ]</button>
                }
            </dd>

        </dl>

    </div>

</div>

src/eShopLegacyMVC/Views/Catalog/Details.cshtml
@model eShopLegacyMVC.Models.CatalogItem

@{
    ViewBag.Title = "Details";
}

<h2 class="esh-body-title">Details</h2>

<div class="container">
    <div class="row">
        <img class="col-md-6 esh-picture" src="@Model.PictureUri" />
        <dl class="col-md-6 dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CatalogBrand.Brand)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CatalogBrand.Brand)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CatalogType.Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CatalogType.Type)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PictureFileName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PictureFileName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AvailableStock)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AvailableStock)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.RestockThreshold)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RestockThreshold)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MaxStockThreshold)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MaxStockThreshold)
            </dd>

        </dl>
    </div>
    <p class="esh-link-list esh-link-item--margin">
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "esh-link-item" }) |
        @Html.ActionLink("Back to List", "Index", null, new { @class = "esh-link-item" })
    </p>
</div>

src/eShopLegacyMVC/Views/Catalog/Edit.cshtml
@model eShopLegacyMVC.Models.CatalogItem

@{
    ViewBag.Title = "Edit";
}

<h2 class="esh-body-title">Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row">
            <img class="col-md-6 esh-picture" src="@Model.PictureUri" />
            <div class="col-md-6 form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CatalogBrandId, "CatalogBrandId", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownList("CatalogBrandId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CatalogBrandId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CatalogTypeId, "CatalogTypeId", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownList("CatalogTypeId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CatalogTypeId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PictureFileName, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PictureFileName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", Title = "Not allowed for edition" } })
                        @Html.ValidationMessageFor(model => model.PictureFileName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AvailableStock, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.AvailableStock, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AvailableStock, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RestockThreshold, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.RestockThreshold, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RestockThreshold, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MaxStockThreshold, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.MaxStockThreshold, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MaxStockThreshold, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12 text-right esh-button-actions">
                        @Html.ActionLink("[ Cancel ]", "Index", null, new { @class = "btn esh-button esh-button-secondary" })
                        <button type="submit" class="btn esh-button esh-button-primary">[ Save ]</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/eShopLegacyMVC/Views/Catalog/Index.cshtml
@model eShopLegacyMVC.ViewModel.PaginatedItemsViewModel<eShopLegacyMVC.Models.CatalogItem>

@{
    ViewBag.Title = "Index";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-2">
            @Html.Action("Index", "CatalogStatistics")
        </div>
        <div class="col-10">
            <div class="esh-table">
                <p class="esh-link-wrapper">
                    @Html.ActionLink("Create New", "Create", null, new { @class = "btn esh-button esh-button-primary" })
                </p>

                @Html.Partial("CatalogTable", Model.Data)

                @Html.Partial("CatalogPaging", Model)
            </div>
        </div>
    </div>
</div>